version: "3.8"
services:
  client:
    build:
      context: ./client

  # api:
  #   container_name: td7-api
  #   build: 
  #     context: api
  #     dockerfile: Dockerfile.prod
  #   ports:
  #     - "3000:80"
  #   environment:
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_PORT=5432
  #     - POSTGRES_DB=td7
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   depends_on:
  #     - postgres

  # postgres:
  #   container_name: td7-postgres
  #   image: postgres
  #   environment:
  #     - POSTGRES_DB=td7
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
